name: Hello
on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Print hello Desouza
      run: echo "Hello Desouza"

    - name: print hello Aylin
      run: echo "Hello Aylin"
    
